#importing necessary libraries

In [1]:
%matplotlib inline
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.metrics import r2_score
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
df1=pd.read_csv("/content/drive/MyDrive/great learning/featurization/car-mpg.csv")
df1.head()

mpg  cyl   disp   hp    wt   acc  yr  origin  car_type  \
0  18.0    8  307.0  130  3504  12.0  70       1         0   
1  15.0    8  350.0  165  3693  11.5  70       1         0   
2  18.0    8  318.0  150  3436  11.0  70       1         0   
3  16.0    8  304.0  150  3433  12.0  70       1         0   
4  17.0    8  302.0  140  3449  10.5  70       1         0   

                    car_name  
0  chevrolet chevelle malibu  
1          buick skylark 320  
2         plymouth satellite  
3              amc rebel sst  
4                ford torino

In [4]:
df1.drop("car_name",axis=1,inplace=True)

In [5]:
df1.head()

mpg  cyl   disp   hp    wt   acc  yr  origin  car_type
0  18.0    8  307.0  130  3504  12.0  70       1         0
1  15.0    8  350.0  165  3693  11.5  70       1         0
2  18.0    8  318.0  150  3436  11.0  70       1         0
3  16.0    8  304.0  150  3433  12.0  70       1         0
4  17.0    8  302.0  140  3449  10.5  70       1         0

In [6]:
df1.origin.replace({1:"america",2:"europe",3:"asia"},inplace=True)

In [7]:
df1.head()

mpg  cyl   disp   hp    wt   acc  yr   origin  car_type
0  18.0    8  307.0  130  3504  12.0  70  america         0
1  15.0    8  350.0  165  3693  11.5  70  america         0
2  18.0    8  318.0  150  3436  11.0  70  america         0
3  16.0    8  304.0  150  3433  12.0  70  america         0
4  17.0    8  302.0  140  3449  10.5  70  america         0

In [8]:
df1=pd.get_dummies(df1,columns=["origin"])

In [9]:
df1.head()

mpg  cyl   disp   hp    wt   acc  yr  car_type  origin_america  \
0  18.0    8  307.0  130  3504  12.0  70         0               1   
1  15.0    8  350.0  165  3693  11.5  70         0               1   
2  18.0    8  318.0  150  3436  11.0  70         0               1   
3  16.0    8  304.0  150  3433  12.0  70         0               1   
4  17.0    8  302.0  140  3449  10.5  70         0               1   

   origin_asia  origin_europe  
0            0              0  
1            0              0  
2            0              0  
3            0              0  
4            0              0

In [10]:
df1=df1.replace("?",np.nan)

In [11]:
df1=df1.apply(lambda x:x.fillna(x.median()),axis=0)

In [12]:
df1.isnull().sum()

mpg               0
cyl               0
disp              0
hp                0
wt                0
acc               0
yr                0
car_type          0
origin_america    0
origin_asia       0
origin_europe     0
dtype: int64

#separate independent and dependent variables

In [13]:
x=df1.drop('mpg',axis=1)
y=df1[["mpg"]]

In [14]:
x.head()

cyl   disp   hp    wt   acc  yr  car_type  origin_america  origin_asia  \
0    8  307.0  130  3504  12.0  70         0               1            0   
1    8  350.0  165  3693  11.5  70         0               1            0   
2    8  318.0  150  3436  11.0  70         0               1            0   
3    8  304.0  150  3433  12.0  70         0               1            0   
4    8  302.0  140  3449  10.5  70         0               1            0   

   origin_europe  
0              0  
1              0  
2              0  
3              0  
4              0

In [15]:
y.head()

mpg
0  18.0
1  15.0
2  18.0
3  16.0
4  17.0

In [16]:
from sklearn import preprocessing
x_scaled=preprocessing.scale(x)
y_scaled=preprocessing.scale(y)
x_scaled

array([[ 1.49819126,  1.0906037 ,  0.67311762, ...,  0.77355903,
        -0.49764335, -0.46196822],
       [ 1.49819126,  1.5035143 ,  1.58995818, ...,  0.77355903,
        -0.49764335, -0.46196822],
       [ 1.49819126,  1.19623199,  1.19702651, ...,  0.77355903,
        -0.49764335, -0.46196822],
       ...,
       [-0.85632057, -0.56103873, -0.53187283, ...,  0.77355903,
        -0.49764335, -0.46196822],
       [-0.85632057, -0.70507731, -0.66285006, ...,  0.77355903,
        -0.49764335, -0.46196822],
       [-0.85632057, -0.71467988, -0.58426372, ...,  0.77355903,
        -0.49764335, -0.46196822]])

In [17]:
y_scaled

array([[-7.06438701e-01],
       [-1.09075062e+00],
       [-7.06438701e-01],
       [-9.62646649e-01],
       [-8.34542675e-01],
       [-1.09075062e+00],
       [-1.21885460e+00],
       [-1.21885460e+00],
       [-1.21885460e+00],
       [-1.09075062e+00],
       [-1.09075062e+00],
       [-1.21885460e+00],
       [-1.09075062e+00],
       [-1.21885460e+00],
       [ 6.21851453e-02],
       [-1.94022803e-01],
       [-7.06438701e-01],
       [-3.22126778e-01],
       [ 4.46497068e-01],
       [ 3.18393094e-01],
       [ 1.90289120e-01],
       [ 6.21851453e-02],
       [ 1.90289120e-01],
       [ 3.18393094e-01],
       [-3.22126778e-01],
       [-1.73127050e+00],
       [-1.73127050e+00],
       [-1.60316652e+00],
       [-1.85937447e+00],
       [ 4.46497068e-01],
       [ 5.74601043e-01],
       [ 1.90289120e-01],
       [ 1.90289120e-01],
       [-5.78334726e-01],
       [-9.62646649e-01],
       [-8.34542675e-01],
       [-5.78334726e-01],
       [-7.06438701e-01],
       [-1.2

In [18]:
x_scaled=pd.DataFrame(x_scaled,columns=x.columns)
x_scaled.head()

cyl      disp        hp        wt       acc        yr  car_type  \
0  1.498191  1.090604  0.673118  0.630870 -1.295498 -1.627426 -1.062235   
1  1.498191  1.503514  1.589958  0.854333 -1.477038 -1.627426 -1.062235   
2  1.498191  1.196232  1.197027  0.550470 -1.658577 -1.627426 -1.062235   
3  1.498191  1.061796  1.197027  0.546923 -1.295498 -1.627426 -1.062235   
4  1.498191  1.042591  0.935072  0.565841 -1.840117 -1.627426 -1.062235   

   origin_america  origin_asia  origin_europe  
0        0.773559    -0.497643      -0.461968  
1        0.773559    -0.497643      -0.461968  
2        0.773559    -0.497643      -0.461968  
3        0.773559    -0.497643      -0.461968  
4        0.773559    -0.497643      -0.461968

In [19]:
y_scaled=pd.DataFrame(y_scaled,columns=y.columns)
y_scaled.head()

mpg
0 -0.706439
1 -1.090751
2 -0.706439
3 -0.962647
4 -0.834543

In [20]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_scaled,y_scaled,test_size=0.30,random_state=1)

here test_size=0.30 indicates that 30% of the total data will be used for testing while 70% of the total data will be used for training.random_state=1 is used to maintain consistency everytime the model is run as the model will split differently everytime we run this code but it will give the same results when the random state=1.

In [21]:
x_train

cyl      disp        hp        wt       acc        yr  car_type  \
350 -0.856321 -0.849116 -1.081977 -0.893172 -0.242570  1.351199  0.941412   
59  -0.856321 -0.925936 -1.317736 -0.847061  2.879909 -1.085858  0.941412   
120 -0.856321 -0.695475  0.201600 -0.121101 -0.024722 -0.815074  0.941412   
12   1.498191  1.983643  1.197027  0.934732 -2.203196 -1.627426 -1.062235   
349 -0.856321 -0.983552 -0.951000 -1.165111  0.156817  1.351199  0.941412   
..        ...       ...       ...       ...       ...       ...       ...   
393 -0.856321 -0.513026 -0.479482 -0.213324  0.011586  1.621983  0.941412   
255 -0.856321 -0.513026 -0.427091 -0.296088 -0.061030  0.538847  0.941412   
72   1.498191  1.061796  1.197027  1.089620 -1.113959 -1.085858 -1.062235   
235 -0.856321 -0.925936 -0.767632 -0.834055  0.955591  0.268063  0.941412   
37   0.320935  0.370411 -0.112746  0.375483 -0.024722 -1.356642 -1.062235   

     origin_america  origin_asia  origin_europe  
350        0.773559    -0.497643      -0.461968  
59        -1.292726    -0.497643       2.164651  
120       -1.292726    -0.497643       2.164651  
12         0.773559    -0.497643      -0.461968  
349       -1.292726     2.009471      -0.461968  
..              ...          ...            ...  
393        0.773559    -0.497643      -0.461968  
255        0.773559    -0.497643      -0.461968  
72         0.773559    -0.497643      -0.461968  
235       -1.292726     2.009471      -0.461968  
37         0.773559    -0.497643      -0.461968  

[278 rows x 10 columns]

In [22]:
x_test

cyl      disp        hp        wt       acc        yr  car_type  \
174  0.320935 -0.215346 -0.191332  0.016051 -0.387801 -0.273506 -1.062235   
359 -0.856321 -0.503423 -0.636655  0.306908  1.754364  1.351199  0.941412   
250  1.498191  1.196232  0.935072  0.903991 -0.859804  0.538847 -1.062235   
274 -0.267693 -0.599449 -0.034159 -0.166030  0.120509  0.538847  0.941412   
283  0.320935  0.370411 -0.374700  0.348290  0.955591  0.809631 -1.062235   
..        ...       ...       ...       ...       ...       ...       ...   
382 -0.856321 -0.820308 -0.898609 -0.857702  0.483588  1.621983  0.941412   
39   1.498191  1.983643  1.851913  1.765921 -1.477038 -1.356642 -1.062235   
171 -0.856321 -0.570641 -0.217527 -0.317370 -0.750880 -0.273506  0.941412   
271 -0.856321 -0.359385  0.018232 -0.266530  0.410972  0.538847  0.941412   
247 -0.856321 -1.041167 -0.898609 -1.064612  1.100822  0.538847  0.941412   

     origin_america  origin_asia  origin_europe  
174        0.773559    -0.497643      -0.461968  
359       -1.292726    -0.497643       2.164651  
250        0.773559    -0.497643      -0.461968  
274       -1.292726    -0.497643       2.164651  
283        0.773559    -0.497643      -0.461968  
..              ...          ...            ...  
382       -1.292726     2.009471      -0.461968  
39         0.773559    -0.497643      -0.461968  
171       -1.292726     2.009471      -0.461968  
271        0.773559    -0.497643      -0.461968  
247       -1.292726     2.009471      -0.461968  

[120 rows x 10 columns]

In [23]:
y_train

mpg
350  1.432898
59  -0.065919
120 -0.578335
12  -1.090751
349  1.356035
..        ...
393  0.446497
255  0.203100
72  -1.090751
235  0.318393
37  -0.706439

[278 rows x 1 columns]

In [24]:
y_test

mpg
174 -0.706439
359  0.587411
250 -0.527093
274 -0.411800
283 -0.424610
..        ...
382  1.343225
39  -1.218855
171  0.062185
271 -0.040298
247  2.034986

[120 rows x 1 columns]

#fit a simple linear model

In [25]:
regm=LinearRegression()
regm.fit(x_train,y_train)

LinearRegression()

In [26]:
regm.coef_

array([[ 0.32102239,  0.32483431, -0.2291695 , -0.71121019,  0.01471368,
         0.37558119,  0.38147695, -0.07472248,  0.04451525,  0.04834855]])

In [27]:
for i in enumerate(x_train.columns):
  print(i)

(0, 'cyl')
(1, 'disp')
(2, 'hp')
(3, 'wt')
(4, 'acc')
(5, 'yr')
(6, 'car_type')
(7, 'origin_america')
(8, 'origin_asia')
(9, 'origin_europe')


In [28]:
for no,name in enumerate(x_train.columns):
  print("the coefficient for {} is {}".format(name,regm.coef_[0][no]))

the coefficient for cyl is 0.32102238569161046
the coefficient for disp is 0.3248343091848398
the coefficient for hp is -0.22916950059437655
the coefficient for wt is -0.7112101905072297
the coefficient for acc is 0.014713682764191029
the coefficient for yr is 0.37558119495107434
the coefficient for car_type is 0.38147694842331054
the coefficient for origin_america is -0.07472247547584163
the coefficient for origin_asia is 0.044515252035678465
the coefficient for origin_europe is 0.04834854953945399


In [29]:
print("intercept for the model is {}".format(regm.intercept_[0]))

intercept for the model is 0.019284116103639733


In [30]:
y_pred=regm.predict(x_test)
y_pred

array([[-0.53114626],
       [ 0.58000872],
       [-0.28618227],
       [ 0.60691934],
       [-0.10856958],
       [-0.83656974],
       [ 0.86612394],
       [ 1.48617281],
       [-0.60033432],
       [-1.58118512],
       [ 0.92691618],
       [-0.63101009],
       [-0.44775729],
       [ 0.41988537],
       [ 1.7249204 ],
       [ 0.00749374],
       [-1.62842071],
       [-0.62516288],
       [-1.82909016],
       [ 1.28766047],
       [ 0.34158378],
       [ 1.10119855],
       [-0.53530813],
       [ 0.25579947],
       [ 0.35735718],
       [ 0.91281065],
       [ 1.21245717],
       [ 1.27266567],
       [-0.92362957],
       [ 0.88592768],
       [ 0.1768598 ],
       [-1.69878378],
       [-0.23657394],
       [ 0.67791148],
       [ 0.26351164],
       [-1.21298076],
       [ 0.46743506],
       [-1.91190633],
       [ 1.09681632],
       [ 0.17397673],
       [ 0.15780247],
       [ 0.20951487],
       [-0.1588762 ],
       [ 1.3451445 ],
       [ 0.00410714],
       [-0

#creating a ridge regularized model

In [31]:
rid=Ridge(alpha=0.3)#alpha controls the degree of regularization if the value is higher , more suppression will take place
rid.fit(x_train,y_train)
print(rid.coef_)

[[ 0.31649043  0.31320707 -0.22876025 -0.70109447  0.01295851  0.37447352
   0.37725608 -0.07423624  0.04441039  0.04784031]]


In [32]:
y_pred1=rid.predict(x_test)

In [33]:
y_pred1

array([[-0.52397331],
       [ 0.58227016],
       [-0.29138559],
       [ 0.60685965],
       [-0.10847923],
       [-0.83871342],
       [ 0.86287483],
       [ 1.48298161],
       [-0.60132015],
       [-1.57844903],
       [ 0.92630211],
       [-0.62956835],
       [-0.44623856],
       [ 0.42320947],
       [ 1.71952947],
       [ 0.01433202],
       [-1.63370883],
       [-0.62058924],
       [-1.8289263 ],
       [ 1.28397831],
       [ 0.34332942],
       [ 1.09788211],
       [-0.53570613],
       [ 0.25773437],
       [ 0.35872511],
       [ 0.90632829],
       [ 1.21119067],
       [ 1.26937958],
       [-0.92634694],
       [ 0.88472821],
       [ 0.17927876],
       [-1.7058346 ],
       [-0.23162179],
       [ 0.67902482],
       [ 0.26522519],
       [-1.21538904],
       [ 0.46838552],
       [-1.91404928],
       [ 1.09625536],
       [ 0.17467351],
       [ 0.15892245],
       [ 0.21277417],
       [-0.16295801],
       [ 1.34287344],
       [ 0.00767291],
       [-0

#lasso model

In [34]:
las=Lasso(alpha=0.03)
las.fit(x_train,y_train)
las.coef_

array([ 0.        , -0.        , -0.04281067, -0.51433744,  0.        ,
        0.33516357,  0.13663366, -0.06692946,  0.        ,  0.        ])

In [35]:
y_pred2=las.predict(x_test)

In [36]:
y_pred2

array([-0.27559954,  0.55046926, -0.50825185,  0.49565469, -0.07560436,
       -0.97397623,  0.68805122,  1.28824159, -0.80538107, -1.47150128,
        0.92717254, -0.76300579, -0.28818265,  0.53691612,  1.47212395,
        0.15905671, -1.66787463, -0.43587227, -1.76716745,  1.12160701,
        0.40342776,  0.97416419, -0.47450188,  0.3028643 ,  0.44824664,
        0.64094126,  1.09122561,  1.06671315, -1.06038423,  0.88171354,
        0.36883738, -1.70045202, -0.12155455,  0.66881973,  0.3381552 ,
       -1.22325257,  0.55243136, -1.79683833,  1.06704106,  0.20087159,
        0.26672999,  0.3279119 , -0.39907774,  1.18964689,  0.23994959,
       -0.25311727, -0.42420211, -1.40860869,  0.65553792, -0.60139131,
        0.21210732,  0.55487414, -0.88997271, -1.36412463,  0.74816489,
        0.29305191, -1.67514732, -1.30697337,  0.86197257,  1.42508189,
        1.40810991,  1.42508189, -0.69279403,  0.41186768, -0.55337474,
        1.12462073,  0.30380261,  0.23281792,  0.8576999 , -1.27

#comparing their scores

The R-squared (R2) score, also known as the coefficient of determination, is a statistical measure used to assess the goodness of fit of a regression model. It indicates the proportion of the variance in the dependent variable (target) that is explained by the independent variables (features) in the model. In other words, R2 quantifies how well the model's predictions match the actual observed values.

The R2 score is a value between 0 and 1. Here's what different R2 values imply:

* R2 = 0: The model explains none of the variability in the target variable. It's as good as predicting the mean of the target for every observation.
* 0 < R2 < 1: The model explains a portion of the variability in the target variable. The closer R2 is to 1, the better the model's predictions align with the actual data.
* R2 = 1: The model perfectly explains all the variability in the target variable. It predicts every observation exactly.
Mathematically, the R2 score is calculated as:

R2 = 1 - (SSR / SST)

Where:

* SSR (Sum of Squared Residuals) is the sum of the squared differences between the predicted values and the actual values.
* SST (Total Sum of Squares) is the sum of the squared differences between the actual values and the mean of the actual values.

The R2 score ranges from 0 to 1, but it's important to note that a high R2 score doesn't necessarily mean the model is good. A high R2 score might indicate overfitting if the model is capturing noise in the data instead of true underlying relationships. Therefore, it's important to consider other evaluation metrics, cross-validation, and domain knowledge when assessing the quality of a regression model.

In [37]:
print(regm.score(x_train,y_train))
print(regm.score(x_test,y_test))

0.8343770256960538
0.8513421387780067


In [38]:
print(rid.score(x_train,y_train))
print(rid.score(x_test,y_test))

0.8343617931312616
0.8518882171608504


In [39]:
print(las.score(x_train,y_train))
print(las.score(x_test,y_test))

0.8109793067067186
0.854478439038032


we get similar accuracy with all 3 models but in lasso we are using only 5 attributes so the lasso model is less complex as compared to the other 2.

#generating polynomial features

generating polynomial features means it takes the existing 10 dimensions , understands the relation between them and then creates more dimensions based on the relations between them.

In [40]:
from sklearn.preprocessing import PolynomialFeatures

In [41]:
poly=PolynomialFeatures(degree=2,interaction_only=True)

degree=2 here means that a dimension can be created which is the original dimension raised to power 2 but not more than that.

interaction_only=True means that only the dimensions showing some kind of interaction or correlation between them will be taken.



In [42]:
x_poly=poly.fit_transform(x_scaled)

In [43]:
x_train,x_test,y_train,y_test=train_test_split(x_poly,y,test_size=0.30,random_state=1)
x_train.shape

(278, 56)

In [46]:
x_train

array([[ 1.        , -0.85632057, -0.8491159 , ..., -0.38495651,
        -0.35735969,  0.22989541],
       [ 1.        , -0.85632057, -0.92593647, ...,  0.64331658,
        -2.79830109, -1.07722421],
       [ 1.        , -0.85632057, -0.69547474, ...,  0.64331658,
        -2.79830109, -1.07722421],
       ...,
       [ 1.        ,  1.49819126,  1.06179598, ..., -0.38495651,
        -0.35735969,  0.22989541],
       [ 1.        , -0.85632057, -0.92593647, ..., -2.59769606,
         0.5971984 , -0.92831185],
       [ 1.        ,  0.32093534,  0.37041078, ..., -0.38495651,
        -0.35735969,  0.22989541]])

In [47]:
y_train

mpg
350  34.7
59   23.0
120  19.0
12   15.0
349  34.1
..    ...
393  27.0
255  25.1
72   15.0
235  26.0
37   18.0

[278 rows x 1 columns]

In [48]:
x_test

array([[ 1.        ,  0.32093534, -0.21534613, ..., -0.38495651,
        -0.35735969,  0.22989541],
       [ 1.        , -0.85632057, -0.50342329, ...,  0.64331658,
        -2.79830109, -1.07722421],
       [ 1.        ,  1.49819126,  1.19623199, ..., -0.38495651,
        -0.35735969,  0.22989541],
       ...,
       [ 1.        , -0.85632057, -0.5706413 , ..., -2.59769606,
         0.5971984 , -0.92831185],
       [ 1.        , -0.85632057, -0.35938471, ..., -0.38495651,
        -0.35735969,  0.22989541],
       [ 1.        , -0.85632057, -1.04116734, ..., -2.59769606,
         0.5971984 , -0.92831185]])

In [49]:
y_test

mpg
174  18.0
359  28.1
250  19.4
274  20.3
283  20.2
..    ...
382  34.0
39   14.0
171  24.0
271  23.2
247  39.4

[120 rows x 1 columns]

#fitting an unregularized model on poly features

In [44]:
regm.fit(x_train,y_train)
print(regm.coef_)

[[-9.67853872e-13 -3.45886171e+10 -4.44319332e+00 -2.20713292e+00
  -2.95250387e+00 -1.53883744e+00  3.01473348e+00 -4.60540335e+10
  -2.07900267e+10  1.09400877e+11 -8.68487255e+10 -1.26832814e+00
  -1.16659123e+00 -1.35749094e-01  2.81359972e+00 -1.97650100e+00
  -1.10816273e+11 -1.93916592e+11 -7.12573640e+10 -6.80153296e+10
   3.85037368e-01  1.71579269e-01 -5.25571363e-01  3.49994333e+00
  -2.04658007e+00 -2.62191546e+10 -2.16090047e+10 -2.06258483e+10
   1.83546538e-01 -6.24509796e-01 -1.89501969e+00 -5.63179799e-01
  -1.08850675e+10 -8.97113113e+09 -8.56296678e+09 -1.93246841e-01
   5.19730568e-01 -3.53975296e+00  4.92858486e+10  4.06198503e+10
   3.87717472e+10  5.21789551e-01  1.75518036e+00  9.36501148e+09
   7.71834867e+09  7.36718284e+09  3.74290466e-01  6.87454454e+09
   5.66578394e+09  5.40800475e+09 -2.72196349e+10  2.96019913e+10
   2.82551736e+10  7.01517623e+09 -1.44902352e+11  8.29552777e+10]]


In [45]:
regm.predict(x_test)

array([[21.54763794],
       [29.53445435],
       [17.28921509],
       [25.95431519],
       [22.45767212],
       [16.15835571],
       [33.05349731],
       [37.83755493],
       [18.01858521],
       [13.32452393],
       [30.6633606 ],
       [18.76361084],
       [22.19506836],
       [25.65899658],
       [40.44567871],
       [21.37496948],
       [13.00881958],
       [19.0585022 ],
       [13.1060791 ],
       [34.95587158],
       [22.97915649],
       [32.29190063],
       [18.15115356],
       [27.37225342],
       [21.95455933],
       [30.61380005],
       [33.55258179],
       [35.7098999 ],
       [16.86032104],
       [30.45611572],
       [20.09893799],
       [14.20770264],
       [17.91546631],
       [26.19387817],
       [23.90426636],
       [13.19732666],
       [27.77780151],
       [13.07907104],
       [34.21365356],
       [23.08267212],
       [26.96868896],
       [23.8588562 ],
       [18.51681519],
       [34.0005188 ],
       [21.66644287],
       [22

In [50]:
rid=Ridge(alpha=0.3)
rid.fit(x_train,y_train)
rid.coef_

array([[ 0.        ,  3.73512981, -2.93500874, -2.13974194, -3.56547812,
        -1.28898893,  3.01290805,  2.04739082,  0.0786974 ,  0.21972225,
        -0.3302341 , -1.46231096, -1.17221896,  0.00856067,  2.48054694,
        -1.67596093,  0.99537516, -2.29024279,  4.7699338 , -2.08598898,
         0.34009408,  0.35024058, -0.41761834,  3.06970569, -2.21649433,
         1.86339518, -2.62934278,  0.38596397,  0.12088534, -0.53440382,
        -1.88265835, -0.7675926 , -0.90146842,  0.52416091,  0.59678246,
        -0.26349448,  0.5827378 , -3.02842915, -0.36548074,  0.5956112 ,
        -0.15941014,  0.49168856,  1.45652375, -0.43819158, -0.20964198,
         0.77665496,  0.36489921, -0.4750838 ,  0.3551047 ,  0.23188557,
        -1.42941282,  2.06831543, -0.34986402, -0.32320394,  0.39054656,
         0.06283411]])

In [51]:
rid.predict(x_test)

array([[21.41209786],
       [29.55681759],
       [17.34069646],
       [26.03369204],
       [22.47945709],
       [16.12630034],
       [32.94938517],
       [37.61921835],
       [17.97801623],
       [13.31940285],
       [30.59388635],
       [18.56240015],
       [22.0648674 ],
       [25.53844185],
       [40.39902367],
       [21.3962499 ],
       [13.16620361],
       [19.024125  ],
       [13.17042724],
       [35.06442161],
       [23.11185877],
       [32.2745463 ],
       [18.21143594],
       [26.38757969],
       [21.98918702],
       [30.64704086],
       [33.51672995],
       [35.45086358],
       [16.71595239],
       [30.24583936],
       [20.58288065],
       [14.27365584],
       [18.04996016],
       [26.48315821],
       [23.96314439],
       [13.26014078],
       [27.77664207],
       [13.08921335],
       [34.07488281],
       [23.15860994],
       [26.88538281],
       [23.95414122],
       [18.62603901],
       [34.03888254],
       [21.88293867],
       [21

In [73]:
las=Lasso(alpha=0.2)
las.fit(x_train,y_train)
las.coef_

array([ 0.        , -0.        , -0.        , -1.6628868 , -4.86898601,
       -0.        ,  2.74431756,  0.11947885, -0.18006353,  0.        ,
        0.        , -0.        ,  0.        ,  0.        ,  0.        ,
       -0.        ,  0.        ,  0.        ,  0.        , -0.        ,
        0.        ,  1.18114478,  0.        , -0.        , -0.        ,
        0.        ,  0.        , -0.        ,  0.09447993,  0.        ,
       -0.72119245, -0.        ,  0.        , -0.        , -0.        ,
       -0.        , -0.        , -0.        ,  0.        , -0.        ,
       -0.01114452,  0.        , -0.        , -0.44181279,  0.        ,
        0.33175685,  0.        , -0.22629489,  0.        ,  0.        ,
       -0.        , -0.        ,  0.03719036,  0.        , -0.        ,
       -0.        ])

In [74]:
las.predict(x_test)

array([21.38340148, 28.70681589, 18.54819023, 25.15749184, 22.59116295,
       15.6181908 , 31.70611296, 36.25799742, 17.11965228, 12.77941808,
       30.43438204, 16.21612964, 20.19418687, 24.1031117 , 38.79696582,
       21.44884984, 14.13869281, 19.68768077, 13.1023245 , 34.55310247,
       24.82046485, 31.33134774, 19.87744112, 24.24344024, 24.57027162,
       31.47166361, 32.91985655, 34.64485004, 15.96297678, 29.59718163,
       25.44130408, 14.55929579, 21.248424  , 26.9004994 , 24.77219126,
       14.18221846, 27.69459955, 13.28118182, 32.74175375, 24.02793355,
       25.41638325, 24.69515056, 19.52632747, 33.43139762, 25.24709046,
       20.85336233, 19.29586909, 13.6209217 , 28.33274436, 17.97148375,
       23.33770256, 25.90767367, 16.72917122, 13.70455047, 29.91710854,
       24.3078544 , 13.53325139, 14.19624118, 31.13682181, 37.15345343,
       36.40623932, 37.25966028, 17.19603582, 26.78220121, 18.26813213,
       32.95764673, 26.16396747, 25.50729945, 29.91949577, 13.50

#checking scores

In [56]:
print(regm.score(x_train,y_train))
print(regm.score(x_test,y_test))

0.9150553186137941
0.8587339450004422


In [57]:
print(rid.score(x_train,y_train))
print(rid.score(x_test,y_test))

0.9143225702003367
0.861339805369855


In [75]:
print(las.score(x_train,y_train))
print(las.score(x_test,y_test))

0.8813629188268554
0.8831400804037386
